Repository AmberELEC/AmberELEC, pull requests merged in 2021-05, with the labels that each got.

#337 Set standard as standard for psx controller
  packages/games/libretro/retroarch/sources/retroarch-core-options.cfg
Labels: enhancement

#335 RG351V Theme Updates Part 1, Clean Up, New metadata for Remove ._ files
  metadata/RG351P/themes.cfg
  metadata/RG351V/images/rg351p Hotkeys 351ELEC purple.jpg
  metadata/RG351V/images/rg351p Hotkeys 351ELEC white.jpg
  metadata/RG351V/images/rg351p hotkeys 351ELEC purple.svg
  metadata/RG351V/images/rg351p hotkeys 351ELEC white.svg
  metadata/RG351V/themes.cfg
  metadata/RG351V/themes/351ELEC-351Noir.jpg
  metadata/RG351V/themes/351ELEC-Alekfull.jpg
  metadata/RG351V/themes/351ELEC-CRAZYBOY.jpg
  metadata/RG351V/themes/351ELEC-Carbon.jpg
  metadata/RG351V/themes/351ELEC-Chicuelo.jpg
  metadata/RG351V/themes/351ELEC-Comicbook.jpg
  metadata/RG351V/themes/351ELEC-CosmicRise.jpg
  metadata/RG351V/themes/351ELEC-Crystal.jpg
  metadata/RG351V/themes/351ELEC-EpicBlancheNoir.jpg
  metadata/RG351V/themes/351ELEC-EpicCody.jpg
  metadata/RG351V/themes/351ELEC-Fundamental.jpg
  metadata/RG351V/themes/351ELEC-Pixel.jpg
  metadata/RG351V/themes/351ELEC-Roleta.jpg
  metadata/RG351V/themes/351ELEC-SpinMaster.jpg
  metadata/RG351V/themes/351ELEC-SuperSweet.jpg
  metadata/RG351V/themes/351ELEC-Supreme.jpg
  metadata/RG351V/themes/351ELEC-Switch.jpg
  metadata/RG351V/themes/Airen.jpg
  metadata/RG351V/themes/Alt-Book.jpg
  metadata/RG351V/themes/Cody-Destroy.jpg
  metadata/RG351V/themes/Epic-Cody.jpg
  metadata/RG351V/themes/Epic-Szalik.jpg
  metadata/RG351V/themes/GBZ.jpg
  metadata/RG351V/themes/Handheld-Simple.jpg
  metadata/RG351V/themes/Horizontal-Szalik.jpg
  metadata/RG351V/themes/Minimal.jpg
  packages/351elec/config/distribution/modules/downloaded_images/clean-thumb.png
  packages/351elec/config/distribution/modules/downloaded_images/clean.png
  packages/351elec/config/distribution/modules/gamelist.xml
  packages/games/ports/sources/images/system-half-life-thumb.png
  packages/games/ports/sources/images/system-half-life.png
  packages/games/ports/sources/images/system-heart_of_darkness-thumb.png
  packages/games/ports/sources/images/system-heart_of_darkness.png
  packages/games/ports/sources/images/system-moonlight-thumb.png
  packages/games/ports/sources/images/system-moonlight.png
  packages/games/ports/sources/images/system-redalert2-thumb.png
  packages/games/ports/sources/images/system-redalert2.png
  packages/games/ports/sources/images/system-steamlink-thumb.png
  packages/games/ports/sources/images/system-steamlink.png
  packages/games/ports/sources/images/system-wolfenstein-thumb.png
  packages/games/ports/sources/images/system-wolfenstein.png
  packages/games/ports/sources/videos/system-redalert2.mp4
  packages/games/ports/sources/videos/system-wolfenstein.mp4
  packages/ui/351elec-emulationstation/package.mk
  packages/ui/351elec-emulationstation/themes/es-theme-handheld-simple/package.mk
Labels: enhancement, help wanted

#334 Adds RetroRun emulator and flycast32_rumble core to improve performance of dreamcast, naomi and atomiswave emulation
  metadata/RG351P/packages.cfg
  metadata/RG351P/packages/retrorun.png
  packages/351elec/sources/scripts/runemu.sh
Labels: enhancement

#348 bump retroarch to 1.9.2 / restore online updater / fix scaling for ozone gui
  packages/games/libretro/retroarch-assets/package.mk
  packages/games/libretro/retroarch/package.mk
  packages/games/libretro/retroarch/patches/0001-Increase-ozone-size.patch
  packages/games/libretro/retroarch/patches/retroarch-04-enablecontent.patch
Labels: documentation, enhancement, help wanted

#350 Fix brightness be reducing stepsize
  packages/351elec/sources/scripts/brightness
Labels: enhancement, help wanted

#338 Fix timezone list
  packages/351elec/sources/scripts/emuelec-utils
Labels: enhancement

#351 fix ES slowdown
  packages/351elec/config/distribution/configs/distribution.conf
  packages/351elec/config/distribution/configs/emuoptions.conf
  packages/351elec/profile.d/99-distribution.conf
  packages/351elec/sources/autostart.sh
  packages/351elec/sources/scripts/emuelec-utils
  packages/351elec/sources/scripts/setemu.sh
  packages/351elec/sources/scripts/setsettings.sh
  packages/ui/351elec-emulationstation/package.mk
Labels: documentation, enhancement, help wanted

#343 Fix avahi autogen ...
  packages/network/avahi/package.mk
Labels: enhancement, help wanted

#341 Fix pyconfig missing when building boost
  packages/devel/boost/package.mk
Labels: enhancement, help wanted

#376 Update themes.cfg
  metadata/RG351V/themes.cfg
Labels: enhancement

#379 RA uses correct TZ
  packages/351elec/sources/scripts/emustation-config
Labels: enhancement
